[connections.postgresql]
dialect = "postgresql"
host = "103.151.242.52"
port = "5432"
database = "dsai"
username = "postgres"
password = "nIV0JOWbNLpZuFk0lHkq1uF02AKvIryLAV9USAvkvLT9AAcoIbFK0ydZGabETOKK"
